apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-data
spec:
  type: url
  targets:
    - https://github.com/mberh/rhdh-catalog/blob/main/domain.yaml
    - https://github.com/mberh/rhdh-catalog/blob/main/group.yaml
    - https://github.com/mberh/rhdh-catalog/blob/main/system.yaml
    - https://github.com/mberh/rhdh-catalog/blob/main/user.yaml
    - https://github.com/mberh/rhdh-catalog/blob/main/component.yaml
