apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: HTTP-testing
  title: Http testing for POST and GET v4.4
  description: Testing http request functionalities with POST and GET
spec:
  owner: a-team
  ownedBy: group:default/a-team
  type: service
  parameters:
    - title: Insert parameters 
      properties:
        functionalArea:
          title: Functional area
          type: string
          description: The functional area of new project
          ui:autofocus: true
        category:
          title: Category
          type: string
          ui:field: DynamicPickExtension
          ui:options:
            # IMPORTANT: The endpoint needs to return a JSON array of strings.
            external_data: https://demo4654476.mockable.io/categories


  steps:
    - id: post-project
      name: Create new project
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/proxy/mockapi/api/v1/project'
        headers:
          content-type: 'application/json'
        body:
          area: ${{ parameters.functionalArea }}
    - id: get-projects
      name: Retrieve all projects
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/mockapi/api/v1/project'
  output:
    text:
    - title: Projects
      content: |
        `${{ steps['get-projects'].output.body | dump}}`
---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: user-info-test
  title: User info testing v3.0
  description: Testing retrive user info
spec:
  owner: a-team
  ownedBy: group:default/a-team
  type: service
  parameters:
    - title: Insert parameters 
      properties:
        functionalArea:
          title: Functional area
          type: string
          description: The functional area of new project
          ui:autofocus: true
        category:
          title: Category
          type: string
          ui:field: DynamicPickExtension
          ui:options:
            # IMPORTANT: The endpoint needs to return a JSON array of strings.
            external_data: https://demo4654476.mockable.io/categories
        componentOwner:
          title: User
          type: string
          description: User that runs the template
          default: ${{ user.ref }}
          # ui:readonly: true
          # ui:widget: hidden
          ui:field: OwnerPicker
         # ui:backstage:
           # review:
           #   show: false

  steps:
    - id: log-hello-ref
      name: Say hello to the logged in user
      action: debug:log
      input:
        message: Hello ${{ user.ref }}      
  output:
    text:
    - title: Projects
      content: |
        `${{ steps['get-projects'].output.body | dump}}`
---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: conditional-step
  title: Conditional step v1.0
  description: test conditional fields 
spec:
  owner: a-team
  ownedBy: group:default/a-team
  type: service
  parameters:
    - title: Choose if last name is required 
      properties:
        includeLast:
          title: Include last name?
          type: boolean
          default: true
    - title: Write your name
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
      # 1. Conditional Field
        lastName:
          title: Last Name (Conditional)
          type: string
          description: Please enter your last name (only visible if 'Include Last Name' was checked).
          
          # KEY USAGE: ui:visibility: ${{ parameters.includeLast }}
          # This uses JSONata to evaluate a previously gathered parameter.
          # If parameters.includeLast is true, the field is visible.
          # If it's false, the field is hidden, and its default value ("") will be used.
          ui:visibility: ${{ parameters.includeLast }} 
          
          # Make the field required ONLY when it is visible.
          required: true 
          
          # When using visibility on a field that exists in a previous step (like we did for lastName), 
          # RJSF intelligently handles updating the value in the second step.
  steps:
    - id: log-hello-ref
      name: Say hello
      action: debug:log
      input:
        message: Hello ${{ parameters.lastName }}      
  output:
    text:
    - title: Projects
      content: |
        `${{ steps['get-projects'].output.body | dump}}`
