---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: handle-yaml
  title: Handle YAML file v2.4
  description: Example template to retrieve and manipulate a YAML file
spec:
  owner: roadie
  type: service

  parameters:
    - title: Repository
      required:
        - url
      properties:
        url:
          title: URL
          type: string
          description: URL of the repo
        filePath:
          title: YAML file 
          type: string
          description: The relative path to the yaml file
    - title: Values
      required:
        - name
        - namespace
      properties:
        name:
          title: Name
          type: string
          description: The name of the component
        namespace: 
          title: Namespace
          type: string
          description: The Openshift Namespace
        reqCpu:
          title: Requested cpu (millicore)
          type: number
          maximum: 800
          minimum: 10
          default: 100
      
  steps:
    - id: fetch
      name: Fetch repo
      action: fetch:plain
      input:
        url: ${{ parameters.url }}
    - id: update-name
      name: Update name
      action: roadiehq:utils:merge
      input:
        path: ${{ parameters.filePath }}
        content:
          name: ${{ parameters.name }}
    - id: update-namespace
      name: Update namespace
      action: roadiehq:utils:merge
      input:
        path: ${{ parameters.filePath }}
        content:
          namespace: ${{ parameters.namespace }}
    - id: update-cpu
      name: Update CPU
      action: roadiehq:utils:merge
      input:
        path: ${{ parameters.filePath }}
        content:
          resources:
            limits:
              cpu: ${{ parameters.cpu }}
    - id: read
      name: Read file
      action: roadiehq:utils:fs:parse
      input:
        path: ${{ parameters.filePath }}
        parser: "yaml"

  output:
    text:
    - title: YAML file
      content: |
           ${{ steps.read.output.content.name }} ${{ steps.read.output.content.resources.limits.cpu }}